### PR TITLE
netmdcli: Format string fixes, fix netmd_get_devname() API in libnetmd

### PR DESCRIPTION
**Pull request by thp**
Two small compiler warning fixes for netmdcli.

### CODE REVIEW

**Comment by karcherm** [comment]
In my oppinion, the interface of netmd_get_devname is broken. libnetmd uses char (not unsigned char) in its public interface for strings in all other places, so expecting netmd_get_devname to accept the address of an char array is a reasonable assumption. netmd_get_devname should include the cast from `char*` (libnetmd convention for strings) to `unsigned char*` (what libusb expects).
The size_t fix is fine.

**Comment by thp** [comment]
Changed the `netmd_get_devname()` API instead and dropped the change in `netmdcli`.

**Comment by glaubitz** [comment]
Builds fine on Debian unstable, tested with gcc-6 and Qt5.

**Comment by karcherm** [comment]
Looks great, can be applied.

**Pull request merged**
