### PR TITLE
Add Hi-MD test data for automated tests

### PR DESCRIPTION
**Pull request by thp**
This contains the Hi-MD folder structure of a disc with 3 Line-In recordings (Hi-SP, Hi-LP, LPCM) and
3 SonicStage uploads (MP3, ATRAC3, ATRAC3Plus).

```
% himdcli testdata/himd tracks
1: 0:07 AT3+ Jahzzar:Siesta Hi-SP Line In (Travellers Guide 0) [uploadable]
2: 0:08 AT3+ Jahzzar:Siesta Hi-LP Line In (Travellers Guide 0) [uploadable]
3: 0:05 LPCM Jahzzar:Siesta LPCM Line In (Travellers Guide 0) [uploadable]
4: 0:07 MPEG Jahzzar:Siesta MP3 SonicStage (Travellers Guide 0) [uploadable]
5: 0:07 AT3  Jahzzar:Siesta ATRAC3 SonicStage (Travellers Guide 0) [uploadable]
6: 0:07 AT3+ Jahzzar:Siesta ATRAC3Plus 192 SonicStage (Travellers Guide 0) [uploadable]
```

### CODE REVIEW

**Comment by karcherm** [comment]
Having a test fixture somewhere around is definitely a good idea. Including it in the main repo and thus doubling the working copy size for everyone - I don't know. Most likely, we will merge this anyway.

**Comment by glaubitz** [comment]
@karcherm What I find more important is the copyright on these files.

@thp Can you please comment on the copyright of the files? We can only merge them if they can be redistributed under a license compatible with Debian's Free Software Guidelines (DFSG).

**Comment by thp** [comment]
That's what the README.TXT file in the merge request is for:

Siesta by Jahzzar is licensed under a Creative Commons Attribution-ShareAlike
3.0 International License.

http://freemusicarchive.org/music/Jahzzar/Travellers_Guide/Siesta

All sound files in the test data are ~ 7-second parts of that track.

**Comment by glaubitz** [comment]
> That's what the README.TXT file in the merge request is for:

Sorry, I missed that part. Then I'm fine merging this as I agree that having testdata is useful.

**Pull request merged**
