### PR TITLE
Continous integration (Linux, macOS, Windows via Linux cross-compilation)

### PR DESCRIPTION
**Pull request by thp**
Here's a summary of what's changed:
- Support for Continous Integration with Travis CI (builds Linux, macOS and Windows 32/64 bit)
- Fix build date detection for cross-compilation
- Make mingw-w64 builds self-contained (build build-dependencies like libmad and gcrypt in CI)
- Remove dependency on `sox` for the GUI and replace with a simple WAV file writer
- Remove (undocumented) dependency on `taglib` for the GUI and replace with a simple ID3v1 writer
- Cleanup the qmake .pro files and split off common parts into .pri files in `build/`
- Detect mounted Hi-MD devices on macOS on startup by scanning /Volumes/ (no monitoring yet)

The build status and build log can be observed at https://travis-ci.org/thp/linux-minidisc, once this is merged, @glaubitz can create an account on travis-ci.org (basically just log in with your Github credentials), and any future pull requests will be built and checked from the original repository as well. In the future, this will allow to automatically build + upload releases to Github Releases (for example) when the master branch is tagged (see https://docs.travis-ci.com/user/deployment/releases).

### CODE REVIEW

**Comment by glaubitz** [comment]
I just had a quick look and noticed that the commit for adding the CI configuration 415cd36 apparently contains unrelated changes to qhimdtransfer like the removal of sox or adding the Hi-MD detection support. Is that intentional?

**Comment by thp** [comment]
The CI configuration commit is a squash commit of all my trial'n'error build commits, one of those was commenting out taglib and sox dependencies so the mingw cross-compilation would work without having to fix building sox and taglib, so yes it's an amalgamation of various smaller changes that were just needed to get the CI build off the ground.

Would you want to have the CI build commit more split apart?

The detection support shouldn't be in that commit from what I can tell.

**Comment by glaubitz** [comment]
Yes, please unbundle the CI build stuff from other changes. It would also be much better to just create PRs for commits which logically belong together otherwise the review process becomes much harder.

Having logically separated commits and PRs allows us to merge changes faster as some changes are easier to review and acknowledge than others. I rather like to get as many changes merged as quick as possible and just leave the difficult PRs open for a more detailed review.

**Comment by thp** [comment]
Split off changes from this PR into the following separate PRs:
- #11 - Replace sox dependency with custom WAV file writer
- #12 - Replace taglib dependency with simple ID3v1 writer
- #13 - Determine build date based on host os, not target
- #14 - Remove unused dependency on id3tag from netmdcli

Once these are merged, we can work the remainder of this PR into two parts, "Project file restructuring" and "Travis CI integration".

**Comment by thp** [comment]
_bump_ -- anyone had time to review the above mentioned PRs already?

**Comment by thp** [comment]
Since most of the small fixes are now merged (or were declined), the remaining parts are now split into two commits:
1. Restructuring the build system (see separate #21 for pull request)
2. After #21 is merged, this pull request contains the Travis CI configuration and build scripts

**Comment by glaubitz** [comment]
This pull request needs to be rebased then, doesn't it? At first look it seems that this PR still contains the changes that you moved into #21.

**Comment by thp** [comment]
Merge after #21.

**Review by glaubitz — APPROVED** [review]

**Review by glaubitz — APPROVED** [review]

**Review by glaubitz — APPROVED** [review]

**Pull request merged**
